### ISSUE TITLE
About the constraints and objectives of MILP

### ISSUE THREAD

**Issue by qsrmlhj** [Grid2op/grid2op-milp-agent#1]
I'm not sure the electrical principles which correspond to the constraints and the objective functions. Are there papers or other information about them? thanks.

**Comment by BDonnot** [comment]
Hello

Nourredine Henka and Sami Tazi have submitted a paper that uses this agent.
As far as I know, the paper is currently being finalized: reviewer comments are taken into account. The paper will be published soon.

We'll reference it as soon as it is publicly available.

Best

Benjamin

**Comment by qsrmlhj** [comment]
Thanks a lot!

**Comment by henkanawro** [comment]
Hello, 

Thank you BDonnot for your reply. As BDonnot mentioned, we have published a paper at PSCC on the topological agent controller https://www.sciencedirect.com/science/article/pii/S0378779622004886. Specifically, we present the topological agent controller based on DC approximation. The set of actions is the electrical power line state control (connected or disconnected) and the electrical bus reconfiguration. Our model has been developed for buses with two substations. Our topological agent controls the grid by minimizing the overload of the power lines.

In addition, we present a distributed topology agent controller. First, the grid is divided into independent zones, then, in each selected zone, a topological agent is installed to control the zone. The whole process is developed in our paper.

Best regards, 

Noureddine

**Comment by EricavanderSar** [comment]
Hello, 

I noticed the Readme file still does not reference the paper of Nourredine. Nor does the paper reference the GitHub page. I think it would be helpful for future researchers if there is a clear link between the two. 

Best wishes,
Erica
